# Generated by Django 2.2.10 on 2021-11-08 14:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AskingModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('question_text', models.CharField(max_length=500)),
                ('start_date', models.DateTimeField(verbose_name='date start')),
                ('finish_date', models.DateTimeField(verbose_name='date finish')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(max_length=200)),
                ('answer_type', models.IntegerField(choices=[('1', 'Текст'), ('2', 'Один вариант'), ('3', 'Несколько вариантов')], default=0)),
                ('answer_choices', models.CharField(blank=True, default='', max_length=500)),
                ('asking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asking.AskingModel')),
            ],
        ),
        migrations.CreateModel(
            name='UserAskings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_finished', models.BooleanField(default=False)),
                ('asking', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='asking.AskingModel')),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='askings_assignedto', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserAnswers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_text', models.CharField(max_length=200)),
                ('answer_is_json', models.BooleanField(default=False)),
                ('question', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='asking.Question')),
                ('user_asking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asking.UserAskings')),
            ],
        ),
    ]
