# Generated by Django 2.2.10 on 2021-11-08 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asking', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='askingmodel',
            name='question_text',
            field=models.CharField(max_length=500, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='question',
            name='answer_type',
            field=models.IntegerField(choices=[(1, 'Текст'), (2, 'Один вариант'), (3, 'Несколько вариантов')], default=1),
        ),
    ]
